export const agencies = [
  { id: 81, name: "TUPINAMBAS, MG" },
  { id: 82, name: "BARREIRO, MG" },
  { id: 83, name: "BARRO PRETO, MG" },
  { id: 84, name: "SECULO, MG" },
  { id: 85, name: "INCONFIDENCIA, MG" },
  { id: 86, name: "FLORESTA, MG" },
  { id: 87, name: "HORTO FLORESTAL, MG" },
  { id: 89, name: "PADRE EUSTAQUIO, MG" },
  { id: 90, name: "IMPERADOR, MG" },
  { id: 91, name: "SAVASSI, MG" },
  { id: 93, name: "SANTA EFIGENIA, MG" },
  { id: 95, name: "ALFENAS, MG" },
  { id: 96, name: "ARAGUARI, MG" },
  { id: 97, name: "ARAXA, MG" },
  { id: 98, name: "BAEPENDI, MG" },
  { id: 99, name: "BARBACENA, MG" },
  { id: 100, name: "BOA ESPERANCA, MG" },
  { id: 101, name: "CAMBUQUIRA, MG" },
  { id: 102, name: "CAMPANHA, MG" },
  { id: 103, name: "CAMPO BELO, MG" },
  { id: 104, name: "CARANDAI, MG" },
  { id: 105, name: "CARANGOLA, MG" },
  { id: 106, name: "CARATINGA, MG" },
  { id: 107, name: "CASSIA, MG" },
  { id: 108, name: "CATAGUASES, MG" },
  { id: 109, name: "CAXAMBU, MG" },
  { id: 110, name: "CONCEICAO DO RIO VERDE, MG" },
  { id: 111, name: "CURVELO, MG" },
  { id: 112, name: "DIAMANTINA, MG" },
  { id: 113, name: "DIVINOPOLIS, MG" },
  { id: 114, name: "ELOI MENDES, MG" },
  { id: 115, name: "FORMIGA, MG" },
  { id: 116, name: "GOVERNADOR VALADARES, MG" },
  { id: 117, name: "GUAXUPE, MG" },
  { id: 118, name: "HORTO DE IPATINGA, MG" },
  { id: 119, name: "ITABIRA, MG" },
  { id: 120, name: "ITABIRITO, MG" },
  { id: 121, name: "ITAJUBA, MG" },
  { id: 122, name: "ITANHANDU, MG" },
  { id: 123, name: "ITAPECERICA, MG" },
  { id: 124, name: "ITAUNA, MG" },
  { id: 125, name: "ITUIUTABA, MG" },
  { id: 126, name: "MANCHESTER, MG" },
  { id: 127, name: "CONSELHEIRO LAFAIETE, MG" },
  { id: 128, name: "LAMBARI, MG" },
  { id: 129, name: "LAVRAS, MG" },
  { id: 131, name: "MANHUACU, MG" },
  { id: 132, name: "MONTES CLAROS, MG" },
  { id: 133, name: "MURIAE, MG" },
  { id: 134, name: "NOVA LIMA, MG" },
  { id: 135, name: "OLIVEIRA, MG" },
  { id: 136, name: "OURO PRETO, MG" },
  { id: 137, name: "PARA DE MINAS, MG" },
  { id: 138, name: "PARACATU, MG" },
  { id: 139, name: "PARAGUACU, MG" },
  { id: 140, name: "PASSA QUATRO, MG" },
  { id: 141, name: "PASSOS, MG" },
  { id: 142, name: "PATOS DE MINAS, MG" },
  { id: 143, name: "PATROCINIO, MG" },
  { id: 144, name: "PEDRO LEOPOLDO, MG" },
  { id: 145, name: "POCOS DE CALDAS, MG" },
  { id: 146, name: "PONTE NOVA, MG" },
  { id: 147, name: "POUSO ALEGRE, MG" },
  { id: 148, name: "SANTANA DO JACARE, MG" },
  { id: 149, name: "SANTOS DUMONT, MG" },
  { id: 150, name: "SAO GONCALO DO SAPUCAI, MG" },
  { id: 151, name: "SAO JOAO DEL REI, MG" },
  { id: 152, name: "SAO LOURENCO, MG" },
  { id: 153, name: "SAO SEBASTIAO DO PARAISO, MG" },
  { id: 154, name: "SETE LAGOAS, MG" },
  { id: 155, name: "TEOFILO OTONI, MG" },
  { id: 156, name: "TRES CORACOES, MG" },
  { id: 157, name: "TRES PONTAS, MG" },
  { id: 158, name: "TUPACIGUARA, MG" },
  { id: 159, name: "UBA, MG" },
  { id: 160, name: "UBERABA, MG" },
  { id: 161, name: "UBERLANDIA, MG" },
  { id: 162, name: "TUBAL VILELA, MG" },
  { id: 163, name: "VARGINHA, MG" },
  { id: 164, name: "VICOSA, MG" },
  { id: 165, name: "VIRGINIA, MG" },
  { id: 166, name: "VISCONDE DO RIO BRANCO, MG" },
  { id: 167, name: "BEIRAMAR, ES" },
  { id: 168, name: "ENSEADA, ES" },
  { id: 169, name: "ALEGRE, ES" },
  { id: 170, name: "AFONSO CLAUDIO, ES" },
  { id: 171, name: "CACHOEIRO DE ITAPEMIRIM, ES" },
  { id: 172, name: "COLATINA, ES" },
  { id: 173, name: "VILA VELHA, ES" },
  { id: 174, name: "NITEROI, RJ" },
  { id: 175, name: "ICARAI, RJ" },
  { id: 176, name: "BARRA MANSA, RJ" },
  { id_177: 177, name: "BARRA DO PIRAI, RJ" },
  { id: 178, name: "BOM JESUS DO ITABAPOANA, RJ" },
  { id: 179, name: "CABO FRIO, RJ" },
  { id: 180, name: "CAMPOS, RJ" },
  { id: 181, name: "DUQUE DE CAXIAS, RJ" },
  { id: 182, name: "ITAPERUNA, RJ" },
  { id: 183, name: "MAGE, RJ" },
  { id: 184, name: "MACAE, RJ" },
  { id: 185, name: "NOVA IGUACU, RJ" },
  { id: 186, name: "NOVA FRIBURGO, RJ" },
  { id: 187, name: "NILOPOLIS, RJ" },
  { id: 188, name: "PETROPOLIS, RJ" },
  { id: 189, name: "RESENDE, RJ" },
  { id: 190, name: "SAO JOAO DE MERITI, RJ" },
  { id: 191, name: "SANTO ANTONIO DE PADUA, RJ" },
  { id: 192, name: "SAO FIDELIS, RJ" },
  { id: 193, name: "TERESOPOLIS, RJ" },
  { id: 194, name: "SAO GONCALO, RJ" },
  { id: 195, name: "TRES RIOS, RJ" },
  { id: 196, name: "VASSOURAS, RJ" },
  { id: 197, name: "VOLTA REDONDA, RJ" },
  { id: 198, name: "LARGO DA CARIOCA, RJ" },
  { id: 199, name: "ALMIRANTE TAMANDARE, RJ" },
  { id: 200, name: "ANCHIETA, RJ" },
  { id: 201, name: "ANDARAI, RJ" },
  { id: 202, name: "BANDEIRA, RJ" },
  { id: 203, name: "BANGU, RJ" },
  { id: 204, name: "BARATA RIBEIRO, RJ" },
  { id: 205, name: "BONSUCESSO, RJ" },
  { id: 206, name: "BOTAFOGO, RJ" },
  { id: 207, name: "AV LOBO JUNIOR, RJ" },
  { id: 208, name: "FREIRE ALEMAO, RJ" },
  { id: 209, name: "GUANABARA, RJ" },
  { id: 210, name: "CASCADURA, RJ" },
  { id: 211, name: "LARANJEIRAS, RJ" },
  { id: 212, name: "COPACABANA, RJ" },
  { id: 213, name: "DEODORO, RJ" },
  { id: 214, name: "PALACIO DO EXERCITO, RJ" },
  { id: 215, name: "ESTRADA DO GALEAO, RJ" },
  { id: 216, name: "COCOTA, RJ" },
  { id: 217, name: "INHANGA, RJ" },
  { id: 218, name: "LEBLON, RJ" },
  { id: 219, name: "MADUREIRA, RJ" },
  { id: 221, name: "MEIER, RJ" },
  { id: 222, name: "PALACIO DA FAZENDA, RJ" },
  { id: 224, name: "PENHA, RJ" },
  { id: 225, name: "PILARES, RJ" },
  { id: 226, name: "URCA, RJ" },
  { id: 228, name: "SAENS PENA, RJ" },
  { id: 229, name: "SANTA CRUZ, RJ" },
  { id: 231, name: "14 BIS, RJ" },
  { id: 232, name: "SAO CRISTOVAO, RJ" },
  { id: 233, name: "VILA ISABEL, RJ" },
  { id: 536, name: "OLEGARIO MACIEL, MG" },
  { id: 537, name: "PRACA JAURU, RJ" },
  { id: 542, name: "RIO DE JANEIRO, RJ" },
  { id: 544, name: "VILA DA PENHA, RJ" },
  { id: 545, name: "RIO SUL, RJ" },
  { id: 555, name: "LINHARES, ES" },
  { id: 556, name: "NOVA VENECIA, ES" },
  { id: 557, name: "GUACUI, ES" },
  { id: 573, name: "LEME, RJ" },
  { id: 588, name: "IPANEMA, RJ" },
  { id: 590, name: "CARIACICA, ES" },
  { id: 591, name: "CASTELO, ES" },
  { id: 592, name: "MUQUI, ES" },
  { id: 603, name: "CRUZILIA, MG" },
  { id: 606, name: "ALMENARA, MG" },
  { id: 607, name: "JOAO MONLEVADE, MG" },
  { id: 608, name: "LEOPOLDINA, MG" },
  { id: 609, name: "PIRAPORA, MG" },
  { id: 625, name: "JUSTICA FEDERAL RIO DE JANEIRO, RJ" },
  { id: 629, name: "CORINTO, MG" },
  { id: 656, name: "PORCIUNCULA, RJ" },
  { id: 660, name: "PAPAGAIOS, MG" },
  { id: 662, name: "UNIVERSIDADE FEDERAL VITORIA, ES" },
  { id: 673, name: "ROCHA MIRANDA, RJ" },
  { id: 680, name: "REALENGO, RJ" },
  { id: 681, name: "MANGABEIRAS, MG" },
  { id: 690, name: "IBIRACU, ES" },
  { id: 691, name: "MACHADO, MG" },
  { id: 694, name: "ANDRADAS, MG" },
  { id: 700, name: "OURO FINO, MG" },
  { id: 704, name: "AIMORES, MG" },
  { id: 705, name: "ARACUAI, MG" },
  { id: 706, name: "CONSELHEIRO PENA, MG" },
  { id: 707, name: "GUANHAES, MG" },
  { id: 708, name: "IBIA, MG" },
  { id: 709, name: "MONTE CARMELO, MG" },
  { id: 710, name: "RAUL SOARES, MG" },
  { id: 716, name: "MONTANHA, ES" },
  { id: 717, name: "SAO MATEUS, ES" },
  { id: 718, name: "BAIXO GUANDU, ES" },
  { id: 719, name: "BARRA DE SAO FRANCISCO, ES" },
  { id: 721, name: "SAO GABRIEL DA PALHA, ES" },
  { id: 769, name: "RIO BONITO, RJ" },
  { id: 770, name: "CARLOS CHAGAS, MG" },
  { id: 771, name: "JANUARIA, MG" },
  { id: 811, name: "ITABORAI, RJ" },
  { id: 815, name: "MINAS GERAIS, MG" },
  { id: 817, name: "CLAUDIO, MG" },
  { id: 821, name: "UFMG, MG" },
  { id: 823, name: "JUCUTUQUARA, ES" },
  { id: 839, name: "MARECHAL MASCARENHAS, RJ" },
  { id: 850, name: "MARATAIZES, ES" },
  { id: 881, name: "GUARAPARI, ES" },
  { id: 882, name: "SERRA, ES" },
  { id: 887, name: "ANGRA DOS REIS, RJ" },
  { id: 888, name: "ARARUAMA, RJ" },
  { id: 889, name: "ALCANTARA, RJ" },
  { id: 892, name: "BETIM, MG" },
  { id: 893, name: "CONTAGEM, MG" },
  { id: 894, name: "CORONEL FABRICIANO, MG" },
  { id: 895, name: "MANHUMIRIM, MG" },
  { id: 896, name: "MANTENA, MG" },
  { id: 909, name: "ITAGUAI, RJ" },
  { id: 925, name: "PARAIBA DO SUL, RJ" },
  { id: 934, name: "FRUTAL, MG" },
  { id: 935, name: "SANTO AGOSTINHO, MG" },
  { id: 936, name: "ITURAMA, MG" },
  { id: 937, name: "JANAUBA, MG" },
  { id: 938, name: "MONTE SANTO DE MINAS, MG" },
  { id: 939, name: "NANUQUE, MG" },
  { id: 940, name: "SACRAMENTO, MG" },
  { id: 941, name: "SANTA RITA DO SAPUCAI, MG" },
  { id: 942, name: "UNAI, MG" },
  { id: 945, name: "VALENCA, RJ" },
  { id: 970, name: "CANTAGALO, RJ" },
  { id: 990, name: "LARGO DO BICAO, RJ" },
  { id: 992, name: "MIGUEL PEREIRA, RJ" },
  { id: 995, name: "RIACHUELO, RJ" },
  { id: 1022, name: "VENDA NOVA, MG" },
  { id: 1023, name: "ALEM PARAIBA, MG" },
  { id: 1024, name: "JACAREPAGUA, RJ" },
  { id: 1025, name: "RAMOS, RJ" },
  { id: 1026, name: "CONDE DE BONFIM, RJ" },
  { id: 1027, name: "LINO TEIXEIRA, RJ" },
  { id: 1034, name: "GOIABEIRAS, ES" },
  { id: 1037, name: "CURICICA, RJ" },
  { id: 1044, name: "CONGONHAS, MG" },
  { id: 1046, name: "JARDIM LIMOEIRO, ES" },
  { id: 1059, name: "ABAETE, MG" },
  { id: 1060, name: "BOM DESPACHO, MG" },
  { id: 1061, name: "CAMBUI, MG" },
  { id: 1062, name: "CAMPINA VERDE, MG" },
  { id: 1063, name: "DORES DO INDAIA, MG" },
  { id: 1064, name: "JACUTINGA, MG" },
  { id: 1065, name: "OURO BRANCO, MG" },
  { id: 1066, name: "SANTA LUZIA, MG" },
  { id: 1067, name: "SAO JOAO NEPOMUCENO, MG" },
  { id: 1093, name: "MUZAMBINHO, MG" },
  { id: 1094, name: "PAVUNA, RJ" },
  { id: 1095, name: "INHAUMA, RJ" },
  { id: 1112, name: "ARACRUZ, ES" },
  { id: 1113, name: "CONCEICAO DA BARRA, ES" },
  { id: 1114, name: "JOAO NEIVA, ES" },
  { id: 1115, name: "IUNA, ES" },
  { id: 1121, name: "MONTE ALEGRE DE MINAS, MG" },
  { id: 1123, name: "RIO POMBA, MG" },
  { id: 1124, name: "SANTA VITORIA, MG" },
  { id: 1149, name: "BELO HORIZONTE, MG" },
  { id: 1235, name: "PRATA, MG" },
  { id: 1243, name: "SAO PEDRO DA ALDEIA, RJ" },
  { id: 1244, name: "MARICA, RJ" },
  { id: 1245, name: "ITAOCARA, RJ" },
  { id: 1246, name: "NATIVIDADE, RJ" },
  { id: 1247, name: "SAO FRANCISCO, RJ" },
  { id: 1255, name: "VIANA, ES" },
  { id: 1306, name: "VENDA NOVA DO IMIGRANTE, ES" },
  { id: 1326, name: "NOSSA SENHORA DA PAZ, RJ" },
  { id: 1327, name: "CATETE, RJ" },
  { id: 1330, name: "SHOPPING VIA BRASIL, RJ" },
  { id: 1331, name: "SAO FRANCISCO DO ITABAPOANA, RJ" },
  { id: 1332, name: "SAQUAREMA, RJ" },
  { id: 1334, name: "25 DE AGOSTO, RJ" },
  { id: 1335, name: "MIRACEMA, RJ" },
  { id: 1336, name: "PARACAMBI, RJ" },
  { id: 1337, name: "FONSECA, RJ" },
  { id: 1339, name: "GAVEA, RJ" },
  { id: 1343, name: "RUA NELSON MANDELA, RJ" },
  { id: 1344, name: "BARRA DA TIJUCA, RJ" },
  { id: 1382, name: "LAGOA DA PRATA, MG" },
  { id: 1384, name: "ITAPEMIRIM, ES" },
  { id: 1411, name: "RIO NORTE, RJ" },
  { id: 1422, name: "BETANIA, MG" },
  { id: 1425, name: "PIUMHI, MG" },
  { id: 1426, name: "POMPEU, MG" },
  { id: 1434, name: "ESTACAO MARECHAL, ES" },
  { id: 1436, name: "MATOZINHOS, MG" },
  { id: 1440, name: "BOM SUCESSO, MG" },
  { id: 1441, name: "CAETE, MG" },
  { id: 1442, name: "CALDAS, MG" },
  { id: 1443, name: "PERDOES, MG" },
  { id: 1458, name: "BARRA BUSINESS, RJ" },
  { id: 1460, name: "LAGOA SANTA, MG" },
  { id: 1461, name: "NOVA ERA, MG" },
  { id: 1462, name: "TIMOTEO, MG" },
  { id: 1470, name: "CAMANDUCAIA, MG" },
  { id: 1474, name: "RIO CASCA, MG" },
  { id: 1475, name: "SANTA BARBARA, MG" },
  { id: 1486, name: "IBIRITE, MG" },
  { id: 1487, name: "PIRAPETINGA, MG" },
  { id: 1488, name: "BICAS, MG" },
  { id: 1491, name: "INHAPIM, MG" },
  { id: 1504, name: "CIDADE DO ACO, RJ" },
  { id: 1507, name: "JOSE CLEMENTE, RJ" },
  { id: 1529, name: "VALE VERDE, MG" },
  { id: 1530, name: "LUXEMBURGO, MG" },
  { id: 1532, name: "CARMO-SION, MG" },
  { id: 1533, name: "MINAS TENIS, MG" },
  { id: 1534, name: "FIDELIS REIS, MG" },
  { id: 1536, name: "MANOEL HONORIO, MG" },
  { id: 1537, name: "MARTINS, MG" },
  { id: 1538, name: "SAO BENEDITO, MG" },
  { id: 1539, name: "AMERICA, ES" },
  { id: 1540, name: "SAO SILVANO, ES" },
  { id: 1564, name: "JARDIM DA PENHA, ES" },
  { id: 1619, name: "MARIO GUIMARAES, RJ" },
  { id: 1620, name: "IGUACUANO, RJ" },
  { id: 1623, name: "OLARIA, RJ" },
  { id: 1624, name: "AV CHILE, RJ" },
  { id: 1639, name: "JARDIM INDUSTRIAL, MG" },
  { id: 1640, name: "CALAFATE, MG" },
  { id: 1641, name: "PADRE CAFE, MG" },
  { id: 1642, name: "IBITURUNA, MG" },
  { id: 1643, name: "GLORIA, ES" },
  { id: 1648, name: "AEROPORTO SANTOS DUMONT, RJ" },
  { id: 1650, name: "SHOPPING CENTER TIJUCA, RJ" },
  { id: 1651, name: "IMPERIAL, RJ" },
  { id: 1667, name: "PARC ROYAL, MG" },
  { id: 1685, name: "BORDA DA MATA, MG" },
  { id: 1686, name: "CONQUISTA, MG" },
  { id: 1687, name: "MARIA DA FE, MG" },
  { id: 1688, name: "MONTE SIAO, MG" },
  { id: 1696, name: "ARCOS, MG" },
  { id: 1697, name: "COROMANDEL, MG" },
  { id: 1698, name: "MATEUS LEME, MG" },
  { id: 1699, name: "PARAISOPOLIS, MG" },
  { id: 1700, name: "PITANGUI, MG" },
  { id: 1701, name: "MARIANA, MG" },
  { id: 1707, name: "PRACA SECA, RJ" },
  { id: 1721, name: "CAMPESTRE, MG" },
  { id: 1724, name: "PRINCESA, MG" },
  { id: 1726, name: "FRANCISCO SA DE MINAS, MG" },
  { id: 1734, name: "SAO JOSE DO CALCADO, ES" },
  { id: 1740, name: "MEDINA, MG" },
  { id: 1742, name: "SABARA, MG" },
  { id: 1745, name: "SALTO DA DIVISA, MG" },
  { id: 1746, name: "PAMPULHA, MG" },
  { id: 1747, name: "LUZ, MG" },
  { id: 1748, name: "PRATAPOLIS, MG" },
  { id: 1776, name: "LARGO DA GLORIA, RJ" },
  { id: 1800, name: "VILA, RJ" },
  { id: 1818, name: "JOAO PINHEIRO, MG" },
  { id: 1820, name: "SAO GOTARDO, MG" },
  { id: 1826, name: "SANTA TERESA, ES" },
  { id: 1830, name: "SALINAS, MG" },
  { id: 1836, name: "ICONHA, ES" },
  { id: 1900, name: "CARMO DO PARANAIBA, MG" },
  { id: 1901, name: "BAMBUI, MG" },
  { id: 1908, name: "MIMOSO DO SUL, ES" },
  { id: 1910, name: "TRIANGULO, MG" },
  { id: 1926, name: "VESPASIANO, MG" },
  { id: 1927, name: "TURFE CLUBE, RJ" },
  { id: 1962, name: "ITAGUACU, ES" },
  { id: 1975, name: "CAMPOS GERAIS, MG" },
  { id: 1978, name: "PADRE ANCHIETA, ES" },
  { id: 2016, name: "BERNARDO HORTA, ES" },
  { id: 2028, name: "VOLUNTARIOS DA PATRIA, RJ" },
  { id: 2030, name: "ENGENHO DE DENTRO, RJ" },
  { id: 2031, name: "SERRA DE SANTA HELENA, MG" },
  { id: 2040, name: "DOMINGOS MARTINS, ES" },
  { id: 2041, name: "CARAPINA, ES" },
  { id: 2042, name: "PRAIA DO CANTO, ES" },
  { id: 2056, name: "PIUMA, ES" },
  { id: 2060, name: "BOM JARDIM, RJ" },
  { id: 2061, name: "CACHOEIRAS DE MACACU, RJ" },
  { id: 2068, name: "MENDES, RJ" },
  { id: 2072, name: "SAPUCAIA, RJ" },
  { id: 2077, name: "PIRAI, RJ" },
  { id: 2123, name: "RUA UBALDINO DO AMARAL, RJ" },
  { id: 2131, name: "JAPERI, RJ" },
  { id: 2146, name: "JACARAIPE, ES" },
  { id: 2161, name: "ALTEROSAS, MG" },
  { id: 2171, name: "PINHEIRAL, RJ" },
  { id: 2180, name: "LARGO DO MARRAO, RJ" },
  { id: 2187, name: "21 DE ABRIL, MG" },
  { id: 2207, name: "PORTO REAL, RJ" },
  { id: 2247, name: "RIO COMPRIDO, RJ" },
  { id: 2255, name: "ABC, MG" },
  { id: 2257, name: "NOVA SERRANA, MG" },
  { id: 2264, name: "DIAS DA CRUZ, RJ" },
  { id: 2270, name: "JARDIM BOTANICO, RJ" },
  { id: 2277, name: "CONCEICAO DO MATO DENTRO, MG" },
  { id: 2279, name: "BAIRRO CEU AZUL, MG" },
  { id: 2296, name: "ACESITA, MG" },
  { id: 2310, name: "HOSPITAL UNIVERSITARIO, ES" },
  { id: 2324, name: "TINDIBA, RJ" },
  { id: 2332, name: "IPATINGA, MG" },
  { id: 2335, name: "JARDIM PRIMAVERA, RJ" },
  { id: 2376, name: "SEPETIBA, RJ" },
  { id: 2381, name: "SISTEMA FIEMG, MG" },
  { id: 2387, name: "PRESIDENTE VARGAS, RJ" },
  { id: 2396, name: "CIDADE DE PRESIDENTE KENNEDY, ES" },
  { id: 2419, name: "MARIANO PROCOPIO, MG" },
  { id: 2423, name: "MERCADO SAO SEBASTIAO, RJ" },
  { id: 2426, name: "ITACOLOMI, MG" },
  { id: 2427, name: "ALIPIO DE MELO, MG" },
  { id: 2432, name: "VILA RICA, MG" },
  { id: 2464, name: "CAPELA NOVA, MG" },
  { id: 2475, name: "CANAAN, MG" },
  { id: 2494, name: "SERGIO PACHECO, MG" },
  { id: 2501, name: "RUA DA ALFANDEGA, RJ" },
  { id: 2503, name: "FINDES, ES" },
  { id: 2519, name: "HALFELD, MG" },
  { id: 2521, name: "JARDIM ITAPOA, ES" },
  { id: 2524, name: "BENTA PEREIRA, RJ" },
  { id: 2538, name: "GRANDE RIO, RJ" },
  { id: 2660, name: "DIGITAL GUANABARA, RJ" },
  { id: 2661, name: "DIGITAL BARRA DA TIJUCA, RJ" },
  { id_2662: 2662, name: "DIGITAL LEBLON, RJ" },
  { id: 2663, name: "DIGITAL MARACANA, RJ" },
  { id: 2699, name: "SESC SENAC NACIONAL, RJ" },
  { id: 2715, name: "EXTREMA, MG" },
  { id: 2732, name: "TRT NITEROI, RJ" },
  { id: 2737, name: "ITAU DE MINAS, MG" },
  { id: 2738, name: "RIO DAS OSTRAS, RJ" },
  { id: 2743, name: "SANTO ANTONIO DO MONTE, MG" },
  { id: 2779, name: "BOCAIUVA, MG" },
  { id: 2781, name: "DIGITAL BAIXADA FLUMINENSE, RJ" },
  { id: 2782, name: "ESMERALDAS, MG" },
  { id: 2784, name: "DIGITAL HORTO DAS ACACIAS, RJ" },
  { id: 2788, name: "DIGITAL NITEROI, RJ" },
  { id: 2808, name: "BRUMADINHO, MG" },
  { id: 2809, name: "SENADOR DANTAS, RJ" },
  { id: 2810, name: "ITATIAIA, RJ" },
  { id: 2834, name: "ROSARIO, RJ" },
  { id: 2837, name: "PORTAL DOS SERTOES, MG" },
  { id: 2838, name: "BARAO DE COCAIS, MG" },
  { id: 2889, name: "VARZEA DA PALMA, MG" },
  { id: 2890, name: "JT RIO DE JANEIRO, RJ" },
  { id: 2904, name: "BARAO DE MESQUITA, RJ" },
  { id: 2905, name: "NEW YORK CITY CENTER, RJ" },
  { id: 2906, name: "TIJUCA, RJ" },
  { id: 2907, name: "DIGITAL OESTE CARIOCA, RJ" },
  { id: 2912, name: "CARDEAL ARCOVERDE, RJ" },
  { id: 2913, name: "AMERICAS, RJ" },
  { id: 2914, name: "PARATY, RJ" },
  { id: 2915, name: "PIO X, RJ" },
  { id: 2922, name: "BELVEDERE, MG" },
  { id: 2923, name: "BURITIS, MG" },
  { id: 2933, name: "MIGUEL DE FRIAS, RJ" },
  { id: 2940, name: "JOAQUIM DE OLIVEIRA, MG" },
  { id: 2954, name: "ARMANDO LOMBARDI, RJ" },
  { id: 2955, name: "RUA AMARAL COSTA, RJ" },
  { id: 2956, name: "PRACA MAUA, RJ" },
  { id: 2973, name: "SHOPPING GRANDE RIO, RJ" },
  { id: 2982, name: "AVENIDA GUILHERME FERREIRA, MG" },
  { id: 2983, name: "LAGOA DO NADO, MG" },
  { id: 2984, name: "CELSO FURTADO, MG" },
  { id: 2986, name: "POLO DA MODA, MG" },
  { id: 3022, name: "PIRATININGA, RJ" },
  { id: 3023, name: "ALMIRANTE GONCALVES, RJ" },
  { id: 3024, name: "DOWNTOWN, RJ" },
  { id: 3025, name: "ITAPARICA, ES" },
  { id: 3028, name: "SHOPPING SAO GONCALO, RJ" },
  { id: 3029, name: "OSCAR VIDAL, MG" },
  { id: 3043, name: "SUL DAS GERAES, MG" },
  { id: 3044, name: "VEREDAS, MG" },
  { id: 3057, name: "MADUREIRA SHOPPING, RJ" },
  { id: 3065, name: "JUIZ DE FORA, MG" },
  { id: 3071, name: "SEROPEDICA, RJ" },
  { id: 3072, name: "TIRADENTES, RJ" },
  { id: 3073, name: "TORRE ALMIRANTE, RJ" },
  { id: 3084, name: "JARDIM CAMBURI, ES" },
  { id: 3092, name: "SHOPPING BAY MARKET, RJ" },
  { id: 3093, name: "PEREIRA PASSOS, RJ" },
  { id: 3105, name: "PECHINCHA, RJ" },
  { id: 3106, name: "RUA DA PASSAGEM, RJ" },
  { id: 3111, name: "JORNALISTA ROBERTO MARINHO, RJ" },
  { id: 3115, name: "SHOPPING MONTES CLAROS, MG" },
  { id: 3131, name: "ATAULFO DE PAIVA, RJ" },
  { id: 3132, name: "COBILANDIA, ES" },
  { id: 3139, name: "LARANJEIRAS DA SERRA, ES" },
  { id: 3146, name: "NORTE SHOPPING, RJ" },
  { id: 3147, name: "03 DE OUTUBRO, RJ" },
  { id: 3148, name: "CIDADE NOBRE, MG" },
  { id: 3152, name: "RONDON PACHECO, MG" },
  { id: 3155, name: "SHOPPING ESTACAO BH, MG" },
  { id: 3174, name: "CORDEIRO, RJ" },
  { id: 3187, name: "SHOPPING BOULEVARD RIO, RJ" },
  { id: 3221, name: "CANDIDES, MG" },
  { id: 3223, name: "PACO IMPERIAL, RJ" },
  { id: 3225, name: "CINELANDIA, RJ" },
  { id: 3234, name: "BAIRRO SANTA RITA, MG" },
  { id: 3238, name: "TOP SHOPPING, RJ" },
  { id: 3239, name: "PELINCA, RJ" },
  { id: 3241, name: "28 DE SETEMBRO, RJ" },
  { id: 3246, name: "RUA SACADURA CABRAL, RJ" },
  { id: 3274, name: "LUIZOTE, MG" },
  { id: 3307, name: "PRAIA DE BOTAFOGO, RJ" },
  { id: 3308, name: "ITACIBA, ES" },
  { id: 3311, name: "DEL REY, MG" },
  { id: 3350, name: "ITAMONTE, MG" },
  { id: 3358, name: "RIO DO A, RJ" },
  { id: 3366, name: "CIDADE DE PINHEIROS, ES" },
  { id: 3376, name: "SAO FRANCISCO DAS PEDRAS, MG" },
  { id: 3377, name: "SAO GONCALO DO RIO ABAIXO, MG" },
  { id: 3378, name: "CAPELINHA, MG" },
  { id: 3380, name: "AV COM ALEXANDRINO GARCIA, MG" },
  { id: 3390, name: "SARAPUI, RJ" },
  { id: 3391, name: "CAVALEIROS, RJ" },
  { id: 3398, name: "PARAIBUNA, MG" },
  { id: 3401, name: "CARMO DO RIO CLARO, MG" },
  { id: 3406, name: "MESQUITA, RJ" },
  { id: 3411, name: "TAIOBEIRAS, MG" },
  { id: 3489, name: "CONCEICAO DE LINHARES, ES" },
  { id: 3517, name: "ESPERA FELIZ, MG" },
  { id: 3526, name: "NEPOMUCENO, MG" },
  { id: 3538, name: "CONCEICAO DAS ALAGOAS, MG" },
  { id: 3539, name: "FERNAO DIAS, MG" },
  { id: 3540, name: "CAPITAL DO MILHO, MG" },
  { id: 3550, name: "JUATUBA, MG" },
  { id: 3551, name: "MANEJO, RJ" },
  { id: 3552, name: "JOAO GUIMARAES ROSA, MG" },
  { id: 3573, name: "SAO JOAO DA BARRA, RJ" },
  { id: 3583, name: "MONSENHOR PAULO, MG" },
  { id: 3590, name: "LEOPOLDINENSE, RJ" },
  { id: 3594, name: "RAUL VEIGA, RJ" },
  { id: 3597, name: "ESTACAO NOVA IGUACU, RJ" },
  { id: 3612, name: "AGUAS FORMOSAS, MG" },
  { id: 3613, name: "RUA DE SANTANA, RJ" },
  { id: 3615, name: "RIBEIRAO DAS NEVES, MG" },
  { id: 3619, name: "POMERANOS, ES" },
  { id: 3630, name: "TREVO, ES" },
  { id: 3637, name: "PARQUE DE MARAPENDI, RJ" },
  { id: 3650, name: "TOCANTINENSE, MG" },
  { id: 3651, name: "CAPINOPOLIS, MG" },
  { id: 3653, name: "ABADIA, MG" },
  { id: 3654, name: "IGARAPE, MG" },
  { id: 3662, name: "VALE DO MUCURI, MG" },
  { id: 3663, name: "BARONESA, MG" },
  { id: 3697, name: "VAZANTE, MG" },
  { id: 3704, name: "MELO VIANA, MG" },
  { id: 3748, name: "CARMO DO CAJURU, MG" },
  { id: 3751, name: "GUARANESIA, MG" },
  { id: 3765, name: "DIGITAL CARIOCA, RJ" },
  { id: 3766, name: "DIGITAL RIO DE JANEIRO CAPITAL, RJ" },
  { id: 3767, name: "DIGITAL SUL FLUMINENSE, RJ" },
  { id: 3773, name: "DIGITAL NORTE FLUMINENSE, RJ" },
  { id: 3797, name: "RESSACA, MG" },
  { id: 3798, name: "LIMA DUARTE, MG" },
  { id: 3813, name: "TRES MARIAS, MG" },
  { id_3814: 3814, name: "SAO CAETANO, MG" },
  { id: 3815, name: "CARMOPOLIS DE MINAS, MG" },
  { id: 3816, name: "MARTINHO CAMPOS, MG" },
  { id: 3820, name: "DIGITAL METROPOLITANA, RJ" },
  { id: 3825, name: "ARMACAO DOS BUZIOS, RJ" },
  { id: 3846, name: "ITAMARANDIBA, MG" },
  { id: 3884, name: "DIGITAL PAO DE ACUCAR, RJ" },
  { id: 3961, name: "VIRGILIO GALASSI, MG" },
  { id: 4014, name: "JUSTICA FEDERAL NOVA FRIBURGO, RJ" },
  { id: 4015, name: "CNC, RJ" },
  { id: 4018, name: "RETIRO, RJ" },
  { id: 4021, name: "TRF RIO DE JANEIRO, RJ" },
  { id: 4022, name: "PETROBRAS IMBETIBA, RJ" },
  { id: 4043, name: "JARDIM OCEANICO, RJ" },
  { id: 4044, name: "TRT 1A REGIAO RIO DE JANEIRO, RJ" },
  { id: 4062, name: "HADDOCK LOBO, RJ" },
  { id: 4063, name: "FREGUESIA, RJ" },
  { id: 4064, name: "TELEPORTO, RJ" },
  { id: 4086, name: "VILA VALQUEIRE, RJ" },
  { id: 4087, name: "RIO OESTE, RJ" },
  { id: 4095, name: "BELFORD ROXO, RJ" },
  { id: 4097, name: "QUEIMADOS, RJ" },
  { id: 4117, name: "FORUM CRIMINAL TRF, RJ" },
  { id: 4118, name: "BRIGADEIRO LIMA E SILVA, RJ" },
  { id: 4119, name: "CONSELHEIRO PAULINO, RJ" },
  { id: 4120, name: "GUARUS, RJ" },
  { id: 4143, name: "PRACA ZE GAROTO, RJ" },
  { id: 4144, name: "AV RIO BRANCO, RJ" },
  { id: 4145, name: "BEIJA-FLOR, RJ" },
  { id: 4146, name: "ITAIPAVA, RJ" },
  { id: 4147, name: "JARDIM DO MEIER, RJ" },
  { id: 4148, name: "RECREIO DOS BANDEIRANTES, RJ" },
  { id: 4149, name: "VILAR DOS TELES, RJ" },
  { id: 4157, name: "SHOPPING CIDADE, MG" },
  { id: 4161, name: "BAIRRO PARAISO, RJ" },
  { id: 4162, name: "NILO PECANHA, RJ" },
  { id: 4192, name: "MUQUICABA, ES" },
  { id: 4193, name: "ROCINHA, RJ" },
  { id: 4203, name: "RECREIO SHOPPING, RJ" },
  { id: 4216, name: "BAIRRO SANTA MONICA, MG" },
  { id: 4262, name: "AG EMPRESARIAL LESTE FLUMINENSE" },
  { id: 4263, name: "AG EMPRESARIAL RIO DE JANEIRO" },
  { id: 4264, name: "AG EMPRESARIAL RIO METROPOLITANA" },
  { id: 4273, name: "AG EMPRESARIAL NORTE FLUMINENSE" },
  { id: 4275, name: "ALPINOPOLIS, MG" },
  { id: 4279, name: "ITAPAGIPE, MG" },
  { id: 4333, name: "IBATIBA, ES" },
  { id: 4337, name: "BARAO DE MIRACEMA, RJ" },
  { id: 4344, name: "SARZEDO, MG" },
  { id: 4345, name: "NOVA PONTE, MG" },
  { id: 4346, name: "FRONTEIRA, MG" },
  { id: 4375, name: "ATERRADO, RJ" },
  { id: 4376, name: "MANILHA, RJ" },
  { id: 4377, name: "COSTA VERDE, RJ" },
  { id: 4382, name: "RIO PARANAIBA, MG" },
  { id: 4383, name: "MATIAS BARBOSA, MG" },
  { id: 4384, name: "SAO JOSE DA LAPA, MG" },
  { id: 4385, name: "JARDIM CANADA, MG" },
  { id: 4386, name: "DA BARRA, MG" },
  { id: 4388, name: "ITATIAIUCU, MG" },
  { id: 4390, name: "LAGOS DE MINAS, MG" },
  { id: 4391, name: "MATIPO, MG" },
  { id: 4392, name: "BELO ORIENTE, MG" },
  { id: 4401, name: "DIVINO, MG" },
  { id: 4402, name: "ESTRADA DOS TRES RIOS, RJ" },
  { id: 4403, name: "JARDIM MARILEIA, RJ" },
  { id: 4415, name: "AV MINISTRO ARI FRANCO, RJ" },
  { id: 4437, name: "BAIRRO SAO CRISTOVAO, RJ" },
  { id: 4448, name: "ITAIPU, RJ" },
  { id: 4456, name: "MONSENHOR FELIX, RJ" },
  { id: 4497, name: "CORPORATIVO RIO DE JANEIRO" },
  { id: 4515, name: "NOVA AMERICA, RJ" },
  { id: 4535, name: "CAMPOS ALTOS, MG" },
  { id: 4536, name: "JEQUITINHONHA, MG" },
  { id: 4537, name: "BAIRRO FOCH, MG" },
  { id: 4543, name: "CACUIA, RJ" },
  { id: 4604, name: "ALFREDO CHAVES, ES" },
  { id: 4607, name: "CENTRAL LARANJEIRAS, ES" },
  { id: 4608, name: "ECOPORANGA, ES" },
  { id: 4642, name: "ITALVA, RJ" },
  { id: 4648, name: "ANIL, RJ" },
  { id: 4650, name: "AVENIDA FELICIANO SODRE, RJ" },
  { id: 4654, name: "VARGEM ALTA, ES" },
  { id: 4655, name: "ESTRADA MANOEL DE SA, RJ" },
  { id: 4659, name: "PARQUE VALENTINA MIRANDA, RJ" },
  { id: 4660, name: "QUISSAMA, RJ" },
  { id: 4706, name: "VILA KOSMOS, RJ" },
  { id: 4724, name: "VILA DE SANTA MARIA, RJ" },
  { id: 4725, name: "INGA, RJ" },
  { id: 4748, name: "AV ABELARDO BUENO, RJ" },
  { id: 4749, name: "OPEN MALL, RJ" },
  { id: 4750, name: "ESTRADA DOS BANDEIRANTES, RJ" },
  { id: 4755, name: "COMENDADOR SOARES, RJ" },
  { id: 4761, name: "PRACA DA MATRIZ, RJ" },
  { id: 4763, name: "ENG PAULO DE FRONTIN, RJ" },
  { id: 4775, name: "RUA DA CANDELARIA, RJ" },
  { id: 4776, name: "TERRA VERMELHA, ES" },
  { id: 4780, name: "LARGO DO LUME, RJ" },
  { id: 4784, name: "ESPINOSA, MG" },
  { id: 4834, name: "QUITUNGO, RJ" },
  { id: 4836, name: "URUGUAI, RJ" },
  { id: 4838, name: "PEQUENA AFRICA, RJ" },
  { id: 4839, name: "QUITANDA, RJ" },
  { id: 4840, name: "RUA DA RELACAO, RJ" },
  { id: 4854, name: "GUAPIMIRIM, RJ" },
  { id: 4867, name: "PRIVATE RIO DE JANEIRO" },
  { id: 4870, name: "CASIMIRO DE ABREU, RJ" },
  { id: 4871, name: "PATY DO ALFERES, RJ" },
  { id: 4872, name: "TANGUA, RJ" },
  { id: 4881, name: "SANTA CRUZ DA SERRA, RJ" },
  { id: 4945, name: "RUA AUGUSTO DE VASCONCELOS, RJ" },
  { id: 4946, name: "GUARATIBA, RJ" },
  { id: 4947, name: "AV DOM HELDER CAMARA, RJ" },
  { id: 4948, name: "ESTACAO LUCAS, RJ" },
  { id: 4971, name: "CSN PATIO SOM, RJ" },
  { id: 4977, name: "QUATIS, RJ" },
  { id: 4978, name: "NOVA CIDADE, RJ" },
  { id: 4979, name: "BURITIS DE MINAS, MG" },
  { id: 4980, name: "JUSTINOPOLIS, MG" },
  { id: 4997, name: "CSN ZONA LESTE, RJ" },
  { id: 5489, name: "DIGITAL CAMPOS, RJ" },
  { id: 7198, name: "TRT CABO FRIO, RJ" },
  { id: 7517, name: "AGRO CAMPOS DOS GOYTACAZES, RJ" },
  { id: 7936, name: "CLUBE DE REGATAS FLAMENGO, RJ" },
  { id: 7947, name: "PETROBRAS RIO, RJ" },
];
