// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
'use client';
import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from 'react';
import { onAuthStateChanged, User } from 'firebase/auth';
import { useFirebase } from '../provider';

/**
 * `AuthContext` provides a way to pass the current user down the component tree.
 *
 * @property {User | null} user - The current authenticated user.
 *
 * @see {@link https://react.dev/learn/passing-data-deeply-with-context | Passing Data Deeply with Context}
 */
const AuthContext = createContext<{ user: User | null }>({ user: null });

/**
 * `AuthProvider` is a React component that listens for authentication state changes and provides the current user to its children.
 *
 * @param {ReactNode} children - The child components to render.
 *
 * @example
 * ```tsx
 * import { AuthProvider } from './firebase/auth/auth-provider';
 *
 * function App({ children }) {
 *   return (
 *     <AuthProvider>
 *       {children}
 *     </AuthProvider>
 *   );
 * }
 * ```
 */
export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const { auth } = useFirebase();
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    if (auth) {
      const unsubscribe = onAuthStateChanged(auth, setUser);
      return () => unsubscribe();
    }
  }, [auth]);

  return (
    <AuthContext.Provider value={{ user }}>{children}</AuthContext.Provider>
  );
};

/**
 * `useAuth` is a custom hook that provides access to the current authenticated user.
 *
 * @returns {{ user: User | null }}
 *
 * @example
 * ```tsx
 * import { useAuth } from './firebase/auth/auth-provider';
 *
 * function MyComponent() {
 *   const { user } = useAuth();
 *   // ...
 * }
 * ```
 */
export const useAuth = () => {
  return useContext(AuthContext);
};

    