// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
'use client';
import { useAuth } from './auth-provider';

/**
 * `useUser` is a custom hook that provides access to the current authenticated user's data.
 *
 * @returns An object containing the current user's data and a boolean indicating if the user is authenticated.
 *
 * @example
 * ```tsx
 * import { useUser } from './firebase/auth/use-user';
 *
 * function MyComponent() {
 *   const { user, isAuthenticated } = useUser();
 *   // ...
 * }
 * ```
 */
export const useUser = () => {
  const { user } = useAuth();
  return {
    user,
    isAuthenticated: !!user,
  };
};

    