// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
'use client';
import { useState, useEffect } from 'react';
import {
  doc,
  onSnapshot,
  DocumentReference,
  DocumentData,
} from 'firebase/firestore';
import { useFirebase } from '../provider';

/**
 * `useDoc` is a custom hook that provides a real-time stream of a document from a Cloud Firestore collection.
 *
 * @param {string | null | undefined} path - The path to the document.
 * @returns An object containing the document data, loading state, and any errors.
 *
 * @example
 * ```tsx
 * import { useDoc } from './firebase/firestore/use-doc';
 *
 * function MyComponent() {
 *   const { data, loading, error } = useDoc('my-collection/my-document');
 *   // ...
 * }
 * ```
 */
export const useDoc = <T extends DocumentData>(
  docRef: DocumentReference<T> | null
) => {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!docRef) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      docRef,
      (snapshot) => {
        if (snapshot.exists()) {
          setData({ id: snapshot.id, ...snapshot.data() } as T);
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [docRef]);

  return { data, loading, error };
};

    