// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
'use client';
import { useState, useEffect } from 'react';
import {
  collection,
  onSnapshot,
  Query,
  DocumentData,
  CollectionReference,
} from 'firebase/firestore';
import { useFirebase } from '../provider';

/**
 * `useCollection` is a custom hook that provides a real-time stream of documents from a Cloud Firestore collection.
 *
 * @param {string | null | undefined} path - The path to the collection.
 * @returns An object containing the collection data, loading state, and any errors.
 *
 * @example
 * ```tsx
 * import { useCollection } from './firebase/firestore/use-collection';
 *
 * function MyComponent() {
 *   const { data, loading, error } = useCollection('my-collection');
 *   // ...
 * }
 * ```
 */
export const useCollection = <T extends DocumentData>(
  query: Query<T> | CollectionReference<T> | null
) => {
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!query) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      query,
      (snapshot) => {
        const data: T[] = snapshot.docs.map(
          (doc) => ({ id: doc.id, ...doc.data() } as T)
        );
        setData(data);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [query]);

  return { data, loading, error };
};

    