// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
export const firebaseConfig = {"projectId":"counter-skp-16476","appId":"1:343416592889:web:11f9780512595ed580536c","storageBucket":"counter-skp-16476.appspot.com","apiKey":"mock-key","authDomain":"counter-skp-16476.firebaseapp.com","messagingSenderId":"343416592889"};

    