// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
'use client';
import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from 'react';
import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';
import { AuthProvider } from './auth/auth-provider';

/**
 * `FirebaseContext` provides a way to pass Firebase app and service instances down the component tree.
 *
 * @property {FirebaseApp | null} app - The Firebase app instance.
 * @property {Auth | null} auth - The Firebase Auth service instance.
 * @property {Firestore | null} firestore - The Cloud Firestore service instance.
 *
 * @see {@link https://react.dev/learn/passing-data-deeply-with-context | Passing Data Deeply with Context}
 */
const FirebaseContext = createContext<{
  app: FirebaseApp | null;
  auth: Auth | null;
  firestore: Firestore | null;
}>({
  app: null,
  auth: null,
  firestore: null,
});

/**
 * `FirebaseProvider` is a React component that initializes Firebase and provides the Firebase app and service instances to its children.
 *
 * @param {ReactNode} children - The child components to render.
 *
 * @example
 * ```tsx
 * import { FirebaseProvider } from './firebase/provider';
 *
 * function App({ children }) {
 *   return (
 *     <FirebaseProvider>
 *       {children}
 *     </FirebaseProvider>
 *   );
 * }
 * ```
 */
export const FirebaseProvider = ({ children }: { children: ReactNode }) => {
  const [app, setApp] = useState<FirebaseApp | null>(null);
  const [auth, setAuth] = useState<Auth | null>(null);
  const [firestore, setFirestore] = useState<Firestore | null>(null);

  useEffect(() => {
    const app = getApps().length ? getApp() : initializeApp(firebaseConfig);

    const auth = getAuth(app);
    const firestore = getFirestore(app);

    setApp(app);
    setAuth(auth);
    setFirestore(firestore);
  }, []);

  return (
    <FirebaseContext.Provider value={{ app, auth, firestore }}>
      <AuthProvider>{children}</AuthProvider>
    </FirebaseContext.Provider>
  );
};

/**
 * `useFirebase` is a custom hook that provides access to the Firebase app and service instances.
 *
 * @returns {{
 *   app: FirebaseApp | null;
 *   auth: Auth | null;
 *   firestore: Firestore | null;
 * }}
 *
 * @example
 * ```tsx
 * import { useFirebase } from './firebase/provider';
 *
 * function MyComponent() {
 *   const { app, auth, firestore } = useFirebase();
 *   // ...
 * }
 * ```
 */
export const useFirebase = () => {
  return useContext(FirebaseContext);
};

    